/**
 * ALMAR Rosario Logistics & Freight Forwarding Portal
 * MAPA PERICIAL DE COTIZACIONES VINCULADAS A CARPETAS ACTIVAS
 * 
 * Basado en la auditoría forense de 1.995 cotizaciones en casillas reales:
 * - Juan Andrés Arloro (jarloro@almarrosario.com / admin@almar.com.ar): Cuentas corporativas y directivas
 * - Lucía Laje (llaje@almarrosario.com / comercial@almar.com.ar): Cotizaciones marítimas FCL/LCL y aéreas
 * - Martín Fusco (mfusco@almarrosario.com): Cuentas LCL y spot regionales (ej. Juan Cuello C367)
 * - Abril Stampfli (astampfli@almarrosario.com): Tráfico terrestre nacional y aéreo exportación
 */

export interface CotizacionVinculada {
  codigo: string;
  cotizacion_id: string;
  responsable_nombre: string;
  responsable_email: string;
  responsable_rol: 'ADMIN' | 'COMERCIAL' | 'GERENCIA' | 'OPERATIVO';
  fecha_emision: string;
  vigencia_dias: number;
  validez_hasta: string;
  incoterm: string;
  dias_libres_demora: number;
  naviera_aerolinea_cotizada: string;
  flete_venta_pactado: number;
  flete_costo_estimado: number;
  margen_proyectado: number;
  moneda: string;
  estado: 'GANADA' | 'COTIZADA' | 'REQUIERE_SEGUIMIENTO';
  notas: string;
}

export const CARPETAS_COTIZACIONES_MAP: Record<string, CotizacionVinculada> = {
  C1234: {
    codigo: 'COT-2026-00060',
    cotizacion_id: 'cot-acin-1234',
    responsable_nombre: 'Juan Andrés Arloro',
    responsable_email: 'jarloro@almarrosario.com',
    responsable_rol: 'ADMIN',
    fecha_emision: '2026-08-10T16:07:49Z',
    vigencia_dias: 30,
    validez_hasta: '2026-09-09T23:59:59Z',
    incoterm: 'FOB Shanghai (CNSHA)',
    dias_libres_demora: 14,
    naviera_aerolinea_cotizada: 'MSC (Mediterranean Shipping Co.) — MSC JEWEL',
    flete_venta_pactado: 3200.0,
    flete_costo_estimado: 2450.0,
    margen_proyectado: 750.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Cotización corporativa cuenta Acindar gestionada directamente por Juan Arloro con confirmación de espacio preferencial MSC.',
  },
  C1434: {
    codigo: 'COT-2026-00061',
    cotizacion_id: 'cot-side-1434',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-07-21T17:15:25Z',
    vigencia_dias: 15,
    validez_hasta: '2026-08-05T23:59:59Z',
    incoterm: 'FOB Ningbo (CNNGB)',
    dias_libres_demora: 14,
    naviera_aerolinea_cotizada: 'Maersk Line A/S — MAERSK MC-KINNEY MOLLER',
    flete_venta_pactado: 1350.0,
    flete_costo_estimado: 848.0,
    margen_proyectado: 502.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'PO Atlas 071 Siderar. Flete marítimo Ningbo a Buenos Aires con 14 días libres en Terminal 4.',
  },
  IT1486: {
    codigo: 'COT-2026-00357',
    cotizacion_id: 'cot-pala-1486',
    responsable_nombre: 'Abril Stampfli',
    responsable_email: 'astampfli@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-08-11T13:42:00Z',
    vigencia_dias: 15,
    validez_hasta: '2026-08-26T23:59:59Z',
    incoterm: 'CPT Villa Gobernador Gálvez',
    dias_libres_demora: 0,
    naviera_aerolinea_cotizada: 'LGV Transportes S.R.L. (Lisandro G. Villalba)',
    flete_venta_pactado: 968000.0,
    flete_costo_estimado: 720000.0,
    margen_proyectado: 248000.0,
    moneda: 'ARS',
    estado: 'GANADA',
    notas: 'Tráfico terrestre enlace portuario TRP Puerto Buenos Aires a planta frigorífica Paladini Villa Gdor Gálvez.',
  },
  C1482: {
    codigo: 'COT-2026-00610',
    cotizacion_id: 'cot-vice-1482',
    responsable_nombre: 'Juan Andrés Arloro',
    responsable_email: 'jarloro@almarrosario.com',
    responsable_rol: 'ADMIN',
    fecha_emision: '2026-08-19T19:38:36Z',
    vigencia_dias: 15,
    validez_hasta: '2026-09-03T23:59:59Z',
    incoterm: 'FCA Ezeiza (EZE)',
    dias_libres_demora: 0,
    naviera_aerolinea_cotizada: 'Lufthansa Cargo / Swiss LX (EZE → FRA)',
    flete_venta_pactado: 5200.0,
    flete_costo_estimado: 4150.0,
    margen_proyectado: 1050.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Exportación aérea urgente muestras de derivados oleaginosos a Frankfurt. Coordinado con agente europeo IMAI.',
  },
  C1024: {
    codigo: 'COT-2026-00226',
    cotizacion_id: 'cot-moli-1024',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-04-10T11:20:00Z',
    vigencia_dias: 30,
    validez_hasta: '2026-05-10T23:59:59Z',
    incoterm: 'FOB Santos, Brasil (BRSSZ)',
    dias_libres_demora: 14,
    naviera_aerolinea_cotizada: 'MSC (Mediterranean Shipping Co.)',
    flete_venta_pactado: 4250.0,
    flete_costo_estimado: 3400.0,
    margen_proyectado: 850.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Carga de insumos alimenticios Santos a Terminal Zárate con escala fluvial a Rosario.',
  },
  TL1436: {
    codigo: 'COT-2026-00379',
    cotizacion_id: 'cot-bung-1436',
    responsable_nombre: 'Abril Stampfli',
    responsable_email: 'astampfli@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-07-29T13:14:09Z',
    vigencia_dias: 15,
    validez_hasta: '2026-08-13T23:59:59Z',
    incoterm: 'CPT Zárate',
    dias_libres_demora: 0,
    naviera_aerolinea_cotizada: 'LGV Transportes / Biton',
    flete_venta_pactado: 540000.0,
    flete_costo_estimado: 410000.0,
    margen_proyectado: 130000.0,
    moneda: 'ARS',
    estado: 'GANADA',
    notas: 'Tramo terrestre interplanta San Lorenzo a Terminal Zárate 12 pallets carga consolidada.',
  },
  C1289: {
    codigo: 'COT-2026-00105',
    cotizacion_id: 'cot-albe-1289',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-06-03T18:46:43Z',
    vigencia_dias: 20,
    validez_hasta: '2026-06-23T23:59:59Z',
    incoterm: 'FOB Bremerhaven / Ningbo',
    dias_libres_demora: 14,
    naviera_aerolinea_cotizada: 'Maersk Line A/S',
    flete_venta_pactado: 1617000.0,
    flete_costo_estimado: 1220000.0,
    margen_proyectado: 397000.0,
    moneda: 'ARS',
    estado: 'GANADA',
    notas: 'Importación piezas industriales con tramo THC liquidado por Terminal 4 y flete marítimo Maersk.',
  },
  EA1561: {
    codigo: 'COT-2026-00428',
    cotizacion_id: 'cot-bert-1561',
    responsable_nombre: 'Abril Stampfli',
    responsable_email: 'astampfli@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-06-01T15:42:57Z',
    vigencia_dias: 15,
    validez_hasta: '2026-06-16T23:59:59Z',
    incoterm: 'FCA Ezeiza / Rosario',
    dias_libres_demora: 0,
    naviera_aerolinea_cotizada: 'Aerolíneas Argentinas Cargo / LATAM Cargo (EZE → MIA)',
    flete_venta_pactado: 11004.04,
    flete_costo_estimado: 9200.0,
    margen_proyectado: 1804.04,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Exportación a Miami de 2 cajones maquinaria pesada (1.030 kg tasables). Despacho en Ezeiza.',
  },
  C1471: {
    codigo: 'COT-2026-00067',
    cotizacion_id: 'cot-secc-1471',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-08-04T15:31:15Z',
    vigencia_dias: 20,
    validez_hasta: '2026-08-24T23:59:59Z',
    incoterm: 'FOB Hamburg, Alemania (DEHAM)',
    dias_libres_demora: 21,
    naviera_aerolinea_cotizada: 'AMA Freight Agency GmbH / Hapag-Lloyd',
    flete_venta_pactado: 10848.55,
    flete_costo_estimado: 8850.0,
    margen_proyectado: 1998.55,
    moneda: 'EUR',
    estado: 'GANADA',
    notas: 'Equipamiento de generación eléctrica Hotstart/Atlas PO 75000669. Retiro coordinado con agente AMA Freight.',
  },
  C1056: {
    codigo: 'COT-2026-00457',
    cotizacion_id: 'cot-sapr-1056',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-04-21T09:22:00Z',
    vigencia_dias: 30,
    validez_hasta: '2026-05-21T23:59:59Z',
    incoterm: 'FOB Buenos Aires',
    dias_libres_demora: 10,
    naviera_aerolinea_cotizada: 'Hapag-Lloyd / MSC (BUE → CTG)',
    flete_venta_pactado: 2800.0,
    flete_costo_estimado: 2240.0,
    margen_proyectado: 560.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Exportación de equipo gráfico Indigo 6K 1x40HC a Cartagena. Sujeto a sobrecosto de flete Hapag auditado.',
  },
  C367: {
    codigo: 'COT-2026-00113',
    cotizacion_id: 'cot-cuel-0367',
    responsable_nombre: 'Martín Fusco',
    responsable_email: 'mfusco@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-07-02T15:58:58Z',
    vigencia_dias: 15,
    validez_hasta: '2026-07-17T23:59:59Z',
    incoterm: 'FOB Guangzhou (CNCAN)',
    dias_libres_demora: 10,
    naviera_aerolinea_cotizada: 'MSL Líneas Marítimas S.A. (Co-Loader)',
    flete_venta_pactado: 680.0,
    flete_costo_estimado: 500.0,
    margen_proyectado: 180.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'LCL importación cafeteras industriales Guangzhou. Retención preventiva y recupero de recargo BUFF USD 80 + IVA.',
  },
  C620: {
    codigo: 'COT-2026-00018',
    cotizacion_id: 'cot-coni-0620',
    responsable_nombre: 'Lucía Laje',
    responsable_email: 'llaje@almarrosario.com',
    responsable_rol: 'COMERCIAL',
    fecha_emision: '2026-03-02T16:38:05Z',
    vigencia_dias: 15,
    validez_hasta: '2026-03-17T23:59:59Z',
    incoterm: 'FCA London Heathrow (LHR)',
    dias_libres_demora: 0,
    naviera_aerolinea_cotizada: 'SAA Logistics UK / British Airways World Cargo',
    flete_venta_pactado: 740.0, // Equivalente oficial BNA de £543 GBP (1.3628)
    flete_costo_estimado: 550.0,
    margen_proyectado: 190.0,
    moneda: 'USD',
    estado: 'GANADA',
    notas: 'Multimoneda GBP con conversión oficial BNA blindada (£543 @ 1.3628 = USD 740.00). Reactivos científicos CONICET.',
  },
};

export function getCotizacionByCarpeta(numeroCarpeta: string): CotizacionVinculada | undefined {
  return CARPETAS_COTIZACIONES_MAP[numeroCarpeta];
}
